services:
  # pipeline to load data from kaggle dataset to PostgreSQL DB
  # NOTE: this will reset the DB by dropping table if they exist
  load_kaggle_data:
    build:
      context: ./load_data
      dockerfile: Dockerfile
    container_name: load_kaggle_data
    volumes: 
      - ./load_data:/choco-project-load-kaggle-data
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env.docker
    profiles: [load]
    restart: "no"
    init: true

  dummy_api:
    build:
      context: ./dummy_api
      dockerfile: Dockerfile
    container_name: dummy_api
    volumes: 
      - ./dummy_api:/choco-project-dummy-api
    depends_on: 
      database:
        condition: service_healthy
    env_file:
      - .env.docker
    profiles: [api]
    restart: unless-stopped
    init: true
    ports: 
      - "127.0.0.1:8000:8000"

  # transform DB's schema (to be completed)
  # note (applies to me only): 
  # alias dbt="docker compose exec transform dbt" was added locally,
  # to run dbt commands do e.g. dbt run, dbt build etc
  transform:
    build:
      context: ./transform
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    container_name: transform
    volumes: 
      - ./transform:/choco-project-transform
    depends_on:
      database:
        condition: service_healthy
      pipeline:
        condition: service_completed_successfully
        required: false
    env_file:
      - .env.docker
    environment:
      DBT_PROJECT_DIR: /choco-project-transform/choco_sales
      DBT_PROFILES_DIR: /choco-project-transform/choco_sales
      DBT_ENGINE_LOG_PATH: /choco-project-transform/choco_sales/logs
      DBT_ENGINE_TARGET_PATH: /choco-project-transform/choco_sales/target
    profiles: [transform]
    restart: "no"
    init: true
    user: "${UID}:${GID}"
    ports: 
      - "127.0.0.1:8080:8080"

  # streamlit dashboard showing data visualization from DB's data
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: dashboard
    volumes: 
      - ./dashboard:/choco-project-dashboard
    ports: 
      - "127.0.0.1:8501:8501"
    depends_on:
      database:
        condition: service_healthy
      load_kaggle_data:
        condition: service_completed_successfully
        required: false
      transform:
        condition: service_completed_successfully
        required: false
    env_file:
      - .env.docker
        
  # PostgreSQL DB
  database:
    image: postgres:18
    container_name: database
    ports:
      - "127.0.0.1:5433:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql
    env_file:
      - .env.docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
      
# volume for PostgreSQL data  
volumes:
  postgres_data: