services:
  db_setup:
    build:
      context: .
      dockerfile: db_setup/Dockerfile
    container_name: db_setup
    volumes:
      - ./db_setup:/choco-project-db-setup/db_setup
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env.docker
    networks:
      - proxy_network

  # pipeline to load data from kaggle dataset to PostgreSQL DB
  # NOTE: this will reset the data by dropping the kaggle data table if they exist
  load_kaggle_data:
    build:
      context: ./load_kaggle_data
      dockerfile: Dockerfile
    container_name: load_kaggle_data
    volumes: 
      - ./load_kaggle_data:/choco-project-load-kaggle-data
    depends_on:
      db_setup:
        condition: service_completed_successfully
    env_file:
      - .env.docker
    #profiles: [load]
    restart: "no"
    init: true
    networks:
      - proxy_network

  online_store_sim:
    build:
      context: ./online_store_simulator
      dockerfile: Dockerfile
    container_name: online_store_sim
    volumes:
      - ./online_store_simulator:/choco-project-online-store-sim
    depends_on:
      dummy_api:
        condition: service_healthy
    env_file:
      - .env.docker
    #profiles: [online_store_sim]
    restart: unless-stopped
    init: true
    networks:
      - proxy_network

  # API for simulated online store
  # available at: http://127.0.0.1:8000 
  # docs are at: http://127.0.0.1:8000/docs 
  dummy_api:
    build:
      context: .
      dockerfile: dummy_api/Dockerfile
    container_name: dummy_api
    volumes: 
      - ./dummy_api:/choco-project-dummy-api/dummy_api
    depends_on: 
      db_setup:
        condition: service_completed_successfully
    env_file:
      - .env.docker
    #profiles: [api]
    restart: unless-stopped
    init: true
    ports: 
      - "127.0.0.1:8000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - proxy_network

  # transform DB's schema (to be completed)
  # note (applies to me only): 
  # ---------- WSL ----------:
  # alias dbt="docker compose exec transform dbt" was added,
  # to run dbt commands do e.g. dbt run, dbt build etc
  # ---------- Windows powershell ----------:
  # function chocddbt { docker compose exec transform dbt @args } was added
  # to run dbt commands in docker use chocddbt run etc
  transform:
    build:
      context: ./transform
      dockerfile: Dockerfile
      # args:
      #   UID: ${UID}
      #   GID: ${GID}
    container_name: transform
    volumes: 
      - ./transform:/choco-project-transform
    depends_on:
      db_setup:
        condition: service_completed_successfully
        required: false
    env_file:
      - .env.docker
    environment:
      DBT_PROJECT_DIR: /choco-project-transform/choco_sales
      DBT_PROFILES_DIR: /choco-project-transform/choco_sales
      DBT_ENGINE_LOG_PATH: /choco-project-transform/choco_sales/logs
      DBT_ENGINE_TARGET_PATH: /choco-project-transform/choco_sales/target
    #profiles: [transform]
    restart: "no"
    init: true
    #user: "${UID}:${GID}"
    ports: 
      - "127.0.0.1:8080:8080"
    networks:
      - proxy_network

  # streamlit dashboard showing data visualization from DB's data
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: dashboard
    volumes: 
      - ./dashboard:/choco-project-dashboard
    ports: 
      - "127.0.0.1:8501:8501"
    depends_on:
      transform:
        condition: service_completed_successfully
        required: false
    env_file:
      - .env.docker
    networks:
      - proxy_network

  # PostgreSQL DB
  database:
    image: postgres:18
    container_name: database
    ports:
      - "127.0.0.1:5433:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql
    env_file:
      - .env.docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - proxy_network

volumes:
  # volume for PostgreSQL data  
  postgres_data:

networks:
  # network to join project and airflow compose
  proxy_network:
    name: airflow_network