-- check if the number of rows in sales table = number of rows in raw table (choco_stats)
SELECT CASE WHEN (SELECT COUNT(*) FROM choco_stats) = (SELECT COUNT(*) FROM sales)
THEN 'PASSED' ELSE 'FAILED' END AS row_count_check;

-- check if sum of boxes shipped is the same between sales table and choco_stats table
SELECT CASE WHEN (SELECT SUM(boxes_shipped) FROM choco_stats) = (SELECT SUM(boxes_shipped) FROM sales)
THEN 'PASSED' ELSE 'FAILED' END AS boxes_shipped_sum_check;

-- check if sum of sales amount is the same between sales table and choco_stats table
SELECT CASE WHEN (SELECT ROUND(SUM(sales_amount_usd)::numeric, 2) FROM choco_stats) = (SELECT ROUND(SUM(sales_amount_usd), 2) FROM sales)
THEN 'PASSED' ELSE 'FAILED' END AS sales_amount_sum_check;

-- check if number of distinct country is the same between sales table and choco_stats table
SELECT CASE WHEN (SELECT COUNT(DISTINCT country) FROM choco_stats) = (SELECT COUNT(*) FROM country) 
THEN 'PASSED' ELSE 'FAILED' END AS country_count_check;

-- check if distinct countries in choco_stats match countries in country table
WITH choco_stats_countries AS(
    SELECT DISTINCT country
    FROM choco_stats 
),
countries AS(
    SELECT name FROM country AS country
)

SELECT CASE WHEN NOT EXISTS(
            SELECT * FROM choco_stats_countries 
            EXCEPT
            SELECT * FROM countries
        ) AND NOT EXISTS(
            SELECT * FROM countries 
            EXCEPT
            SELECT * FROM choco_stats_countries
        )
        THEN 'PASSED'
        ELSE 'FAILED'
END AS countries_match_check;

-- check if number of distinct product is the same between sales table and choco_stats table
SELECT CASE WHEN (SELECT COUNT(DISTINCT product) FROM choco_stats) = (SELECT COUNT(*) FROM product) 
THEN 'PASSED' ELSE 'FAILED' END AS product_count_check;

-- check if distinct products in choco_stats match products in product table
WITH choco_stats_products AS(
    SELECT DISTINCT product
    FROM choco_stats 
),
products AS(
    SELECT name FROM product AS product
)

SELECT CASE WHEN NOT EXISTS(
            SELECT * FROM choco_stats_products 
            EXCEPT
            SELECT * FROM products
        ) AND NOT EXISTS(
            SELECT * FROM products
            EXCEPT
            SELECT * FROM choco_stats_products
        )
        THEN 'PASSED'
        ELSE 'FAILED'
END AS products_match_check;

-- check if number of distinct sales people is the same between sales table and choco_stats table
SELECT CASE WHEN (SELECT COUNT(DISTINCT sales_person) FROM choco_stats) = (SELECT COUNT(*) FROM sales_person) 
THEN 'PASSED' ELSE 'FAILED' END AS sales_person_count_check;

-- check if distinct sales people in choco_stats match sales people in sales_person table
WITH choco_stats_sales_people AS(
    SELECT DISTINCT sales_person
    FROM choco_stats 
),
sales_people AS(
    SELECT name FROM sales_person AS sales_person
)

SELECT CASE WHEN NOT EXISTS(
            SELECT * FROM choco_stats_sales_people
            EXCEPT
            SELECT * FROM sales_people
        ) AND NOT EXISTS(
            SELECT * FROM sales_people
            EXCEPT
            SELECT * FROM choco_stats_sales_people
        )
        THEN 'PASSED'
        ELSE 'FAILED'
END AS sales_people_match_check;

-- check if null foreign keys exist in sales table
SELECT CASE WHEN COUNT(*) = 0 THEN 'PASSED' ELSE 'FAILED' END AS null_fk_check
FROM sales WHERE product_id IS NULL OR 
                 country_id IS NULL OR 
                 sales_person_id IS NULL;

-- check with sample data (top 5 most boxes shipped)
WITH choco_stats_top_boxes_shipped AS(
    SELECT product,
           country,
           sales_person,
           sales_amount_usd,
           boxes_shipped,
           date
    FROM choco_stats 
    ORDER BY boxes_shipped DESC
    LIMIT 5
),
sales_top_boxes_shipped AS(
    SELECT p.name AS product,
           c.name AS country,
           sp.name AS salesperson,
           s.sales_amount_usd,
           s.boxes_shipped,
           s.date
    FROM sales s
    JOIN product p ON s.product_id = p.id
    JOIN country c ON s.country_id = c.id
    JOIN sales_person sp ON s.sales_person_id = sp.id
    ORDER BY s.boxes_shipped DESC
    LIMIT 5
)

SELECT CASE WHEN NOT EXISTS(
            SELECT * FROM choco_stats_top_boxes_shipped
            EXCEPT
            SELECT * FROM sales_top_boxes_shipped
        ) AND NOT EXISTS(
            SELECT * FROM sales_top_boxes_shipped
            EXCEPT
            SELECT * FROM choco_stats_top_boxes_shipped
        )
        THEN 'PASSED'
        ELSE 'FAILED'
END AS sample_data_check_with_top_5_boxes_shipped;