version: 2

sources:
  - name: choco_db_kaggle_hist
    database: choco_db
    schema: kaggle_hist_data
    tables:
      - name: choco_stats
        columns: 
          - name: Sales Person
          - name: Country
          - name: Product
          - name: Date
          - name: Amount
          - name: Boxes Shipped

models:
  - name: stg_choco_db__choco_stats
    description: "Cleaned raw sales records table"
    columns: 
      - name: sales_person
        data_type: varchar(100)
        data_tests: 
          - not_null
      - name: country
        data_type: varchar(100)
        data_tests: 
          - not_null
      - name: product
        data_type: varchar(100)
        data_tests:
          - not_null
      - name: date
        data_type: date
        data_tests: 
          - not_null
      - name: sales_amount_usd
        data_type: decimal
        data_tests: 
          - not_null
      - name: boxes_shipped
        data_type: integer
        data_tests: 
          - not_null