version: 2

sources:
  - name: kaggle_hist
    database: choco_db
    schema: kaggle_hist_data
    tables:
      - name: choco_stats
        description: "Raw chocolate sales data (2022-2024) from Kaggle"
        columns: 
          - name: Sales Person
          - name: Country
          - name: Product
          - name: Date
          - name: Amount
          - name: Boxes Shipped
  - name: online_store
    database: choco_db
    schema: oltp_online_store
    tables:
      - name: countries
        columns:
          - name: id
          - name: name
      - name: customers
        columns:
          - name: id
          - name: name
          - name: username
          - name: email
          - name: country_id
      - name: order_items
        columns: 
          - name: id
          - name: product_id
          - name: order_id
          - name: quantity
          - name: price_per_unit_at_purchase
      - name: order_status_history
        columns:
          - name: id
          - name: order_id
          - name: status_id
          - name: updated_at
      - name: orders
        columns:
          - name: id
          - name: created_at
          - name: status_last_updated_at
          - name: current_status_id
          - name: customer_id
          - name: tax_amount
          - name: discount_amount
          - name: shipping_costs_amount
      - name: products
        columns: 
          - name: id
          - name: name
          - name: current_price
      - name: statuses
        columns:
          - name: id
          - name: name

models:
  - name: stg_online_store__countries
    description: "Countries of customers of the online store"
    columns:
      - name: country_id
        data_type: integer
        data_tests: 
          - not_null
          - unique
      - name: country_name
        data_type: varchar(50)
        data_tests: 
          - not_null
          - unique
  - name: stg_online_store__customers
    description: "Customers of the online store"
    columns:
      - name: customer_id
        data_type: integer
        data_tests: 
          - not_null
          - unique
      - name: customer_name
        data_type: varchar(50)
        data_tests: 
          - not_null
      - name: customer_username
        data_type: varchar(50)
        data_tests:
          - not_null
          - unique
      - name: customer_email
        data_type: varchar(100)
        data_tests: 
          - not_null
      - name: customer_country_id
        data_type: integer
        data_tests: 
          - not_null
          - relationships:
              arguments: 
                to: ref('stg_online_store__countries')
                field: country_id
  - name: stg_online_store__products
    description: "Products available in online store"
    columns:
      - name: product_id
        data_type: integer
        data_tests:
          - not_null
          - unique
      - name: product_name
        data_type: varchar(50)
        data_tests:
          - not_null
      - name: product_current_price
        data_type: numeric(10, 3)
        data_tests:
          - not_null
  - name: stg_online_store__statuses
    description: "Available statuses for orders from the online store"
    columns:
      - name: status_id
        data_type: integer
        data_tests:
          - not_null
          - unique
      - name: status_name
        data_type: varchar(50)
        data_tests: 
          - not_null
          - unique
  - name: stg_online_store__orders
    description: "Orders from online store"
    columns:
      - name: order_id
        data_type: integer
        data_tests: 
          - not_null
          - unique
      - name: order_created_at
        data_type: timestamptz
        data_tests:
          - not_null
      - name: order_status_last_updated_at
        data_type: timestamptz
        data_tests:
          - not_null
      - name: order_current_status_id
        data_type: integer
        data_tests:
          - not_null
          - relationships:
              arguments: 
                to: ref('stg_online_store__statuses')
                field: status_id
      - name: order_customer_id
        data_type: integer
        data_tests:
          - not_null
          - relationships:
              arguments: 
                to: ref('stg_online_store__customers')
                field: customer_id
      - name: order_tax_amount_usd
        data_type: numeric(10, 3)
        data_tests:
          - not_null
      - name: order_discount_amount_usd
        data_type: numeric(10, 3)
        data_tests:
          - not_null
      - name: order_shipping_costs_amount_usd
        data_type: numeric(10, 3)
        data_tests: 
          - not_null
  - name: stg_online_store__order_status_history
    description: "Status history for orders from the online store"
    columns: 
      - name: order_status_history_id
        data_type: integer
        data_tests:
          - not_null
          - unique
      - name: order_status_history_order_id
        data_type: integer
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_online_store__orders')
                field: order_id
      - name: order_status_history_status_id
        data_type: integer
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_online_store__statuses')
                field: status_id
      - name: order_status_history_updated_at
        data_type: timestamptz
        data_tests:
          - not_null
  - name: stg_online_store__order_items
    description: "Items ordered in different orders from the online store"
    columns:
      - name: order_item_id
        data_type: integer
        data_tests:
          - not_null
          - unique
      - name: order_item_product_id
        data_type: integer
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_online_store__products')
                field: product_id
      - name: order_item_order_id
        data_type: integer
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_online_store__orders')
                field: order_id
      - name: order_item_quantity
        data_type: integer
        data_tests:
          - not_null
      - name: order_item_price_per_unit_at_purchase
        data_type: numeric(10, 3)
        data_tests:
          - not_null
  - name: stg_kaggle_hist__choco_stats
    description: "Cleaned raw sales records table"
    columns: 
      - name: sales_person
        data_type: varchar(100)
        data_tests: 
          - not_null
      - name: country
        data_type: varchar(50)
        data_tests: 
          - not_null
      - name: product
        data_type: varchar(100)
        data_tests:
          - not_null
      - name: date
        data_type: date
        data_tests: 
          - not_null
      - name: sales_amount_usd
        data_type: decimal
        data_tests: 
          - not_null
      - name: boxes_shipped
        data_type: integer
        data_tests: 
          - not_null