# version: 2

# sources:
#   - name: choco_db
#     database: choco_db
#     schema: public
#     tables:
#       - name: choco_stats
#         columns: 
#           - name: Sales Person
#           - name: Country
#           - name: Product
#           - name: Date
#           - name: Amount
#           - name: Boxes Shipped

# models:
#   # example models for learning/experimenting
#   - name: my_first_dbt_model
#     description: "Sales records where country is New Zealand taken from a sample of 100 records"
#     columns: 
#       - name: Sales Person
#       - name: Country
#       - name: Product
#       - name: Date
#       - name: Amount
#       - name: Boxes Shipped

#   - name: my_second_dbt_model
#     description: "Sales records taken from my_first_dbt_model where product is 50% Dark Bites"
#     columns: 
#       - name: Sales Person
#       - name: Country
#       - name: Product
#       - name: Date
#       - name: Amount
#       - name: Boxes Shipped
